### ISSUE TITLE
Add Ruby installation instructions in documentation

### ISSUE THREAD

**Issue by priyankasingh** [softwaresaved/carpentry-data-analysis#1]
Hi Aleks,

It'll be great if you can add the Ruby installation instruction for both Centos and Ubuntu. I have tested the system on Ruby 2.2.1 and 2.3.1.

You can add instruction for any version you like. 

Please also add instruction to install nokogiri library and push it in staging branch.

Thanks.

**Comment by anenadic** [comment]
I have no Centos and Ubuntu to test on. Only Mac OS. Any contributions welcome.

**Comment by rgaiacs** [comment]
> It'll be great if you can add the Ruby installation instruction for both Centos and Ubuntu. I have tested the system on Ruby 2.2.1 and 2.3.1.

We can use Travis CI to test it. :-)

**Comment by anenadic** [comment]
Yay, we could have a look at Travis, thanks @rgaiacs.

**Comment by anenadic** [comment]
Now tested on ruby 2.5.0 too on Mac OS.

**Comment by anenadic** [comment]
We are moving to python only version of scripts so closing this issue.
