### ISSUE TITLE
Instructors and Workshop maps for other countries

### ISSUE THREAD

**Issue by ctmartins** [softwaresaved/carpentry-data-analysis#16]
The map scripts were developed taking into account the UK institutions so there is no information about other country institutions and, therefore, it is not possible to map the instructors or workshops information related to the institutions.
There should be an option to add an excel file with academic and non academic institutions coordinates in order to be possible to map that information for other countries.
The only map that works with other countries is map_clustered_workshop_venues.py

**Comment by anenadic** [comment]
Mapping workshops work for other countries as they tend to have (latitude, longitude) pairs. For instructors, we map affiliations to the official institution name and their official  (latitude, longitude) gecoorrdinates. This could be an improvement in AMY to have a list of official institutions to choose from.
