### ISSUE TITLE
Create subfolder inside data folder for csv files

### ISSUE THREAD

**Issue by priyankasingh** [softwaresaved/carpentry-data-analysis#2]
Hi Aleksandra,

We are extending the Data Dashboard module to work with Mike's visualisation too. Mike has lots of csv file with similar filename as yours. Steve and I were discussing and we think it's better if you put your worskhop.csv and other csv file in a subfolder. You can put different csv files in different subfolder. My script will copy everything in the repo's data folder to the SSI data folder.

Let me know if you have any questions.

Thanks,
Priyanka

**Comment by anenadic** [comment]
How do you want to name the subfolders?

**Comment by priyankasingh** [comment]
The name of your repo should work or any other name should be fine too.
User going to add the name of the folder and csv name in the data dashboard page as a div attribute. So, as long as it doesn't interfere with any other folder name, it should be fine.

**Comment by anenadic** [comment]
Done, there is a new version of the code in staging branch.
